import {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibVisa,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilBuilding,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilClock,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilDescription,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLayers,
  cilList,
  cilListRich,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTruck,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilEyedropper,
  cilLockUnlocked,
  cilLoop,
  cilStorage,
  cilCart,
  cilMoney,
  cilCash,
  cilPhone,
} from "@coreui/icons";

export const iconSubset = {
  cibCcAmex,
  cibCcApplePay,
  cibCcMastercard,
  cibCcPaypal,
  cibCcStripe,
  cibVisa,
  cibCcVisa,
  cibFacebook,
  cibGoogle,
  cibLinkedin,
  cibSkype,
  cibTwitter,
  cifBr,
  cifEs,
  cifFr,
  cifIn,
  cifPl,
  cifUs,
  cilAlignCenter,
  cilAlignLeft,
  cilAlignRight,
  cilApplicationsSettings,
  cilArrowBottom,
  cilArrowRight,
  cilArrowTop,
  cilBasket,
  cilBell,
  cilBold,
  cilBookmark,
  cilBuilding,
  cilCalculator,
  cilCalendar,
  cilChart,
  cilChartPie,
  cilCheck,
  cilClock,
  cilChevronLeft,
  cilChevronRight,
  cilCloudDownload,
  cilCode,
  cilCommentSquare,
  cilCreditCard,
  cilCursor,
  cilDollar,
  cilDrop,
  cilDescription,
  cilEnvelopeClosed,
  cilEnvelopeOpen,
  cilFile,
  cilHome,
  cilInbox,
  cilIndentDecrease,
  cilIndentIncrease,
  cilItalic,
  cilJustifyCenter,
  cilLayers,
  cilList,
  cilListRich,
  cilListNumbered,
  cilLocationPin,
  cilLockLocked,
  cilMagnifyingGlass,
  cilMap,
  cilMediaPlay,
  cilMenu,
  cilMoon,
  cilNotes,
  cilOptions,
  cilPaperclip,
  cilPaperPlane,
  cilPen,
  cilPencil,
  cilPeople,
  cilPrint,
  cilPuzzle,
  cilReportSlash,
  cilSave,
  cilSettings,
  cilShare,
  cilShareAll,
  cilShareBoxed,
  cilSpeech,
  cilSpeedometer,
  cilSpreadsheet,
  cilStar,
  cilSun,
  cilTruck,
  cilTags,
  cilTask,
  cilTrash,
  cilUnderline,
  cilUser,
  cilUserFemale,
  cilUserFollow,
  cilUserUnfollow,
  cilEyedropper,
  cilLockUnlocked,
  cilLoop,
  cilStorage,
  cilCart,
  cilMoney,
  cilCash,
  cilPhone,
};

export enum IconSubset {
  cibCcAmex = "cibCcAmex",
  cibCcApplePay = "cibCcApplePay",
  cibCcMastercard = "cibCcMastercard",
  cibCcPaypal = "cibCcPaypal",
  cibCcStripe = "cibCcStripe",
  cibVisa = "cibVisa",
  cibCcVisa = "cibCcVisa",
  cibFacebook = "cibFacebook",
  cibGoogle = "cibGoogle",
  cibLinkedin = "cibLinkedin",
  cibSkype = "cibSkype",
  cibTwitter = "cibTwitter",
  cifBr = "cifBr",
  cifEs = "cifEs",
  cifFr = "cifFr",
  cifIn = "cifIn",
  cifPl = "cifPl",
  cifUs = "cifUs",
  cilAlignCenter = "cilAlignCenter",
  cilAlignLeft = "cilAlignLeft",
  cilAlignRight = "cilAlignRight",
  cilApplicationsSettings = "cilApplicationsSettings",
  cilArrowBottom = "cilArrowBottom",
  cilArrowRight = "cilArrowRight",
  cilArrowTop = "cilArrowTop",
  cilBasket = "cilBasket",
  cilBell = "cilBell",
  cilBold = "cilBold",
  cilBookmark = "cilBookmark",
  cilBuilding = "cilBuilding",
  cilCalculator = "cilCalculator",
  cilCalendar = "cilCalendar",
  cilChart = "cilChart",
  cilChartPie = "cilChartPie",
  cilCheck = "cilCheck",
  cilClock = "cilClock",
  cilChevronLeft = "cilChevronLeft",
  cilChevronRight = "cilChevronRight",
  cilCloudDownload = "cilCloudDownload",
  cilCode = "cilCode",
  cilCommentSquare = "cilCommentSquare",
  cilCreditCard = "cilCreditCard",
  cilCursor = "cilCursor",
  cilDollar = "cilDollar",
  cilDrop = "cilDrop",
  cilDescription = "cilDescription",
  cilEnvelopeClosed = "cilEnvelopeClosed",
  cilEnvelopeOpen = "cilEnvelopeOpen",
  cilFile = "cilFile",
  cilHome = "cilHome",
  cilInbox = "cilInbox",
  cilIndentDecrease = "cilIndentDecrease",
  cilIndentIncrease = "cilIndentIncrease",
  cilItalic = "cilItalic",
  cilJustifyCenter = "cilJustifyCenter",
  cilLayers = "cilLayers",
  cilList = "cilList",
  cilListRich = "cilListRich",
  cilListNumbered = "cilListNumbered",
  cilLocationPin = "cilLocationPin",
  cilLockLocked = "cilLockLocked",
  cilMagnifyingGlass = "cilMagnifyingGlass",
  cilMap = "cilMap",
  cilMediaPlay = "cilMediaPlay",
  cilMenu = "cilMenu",
  cilMoon = "cilMoon",
  cilNotes = "cilNotes",
  cilOptions = "cilOptions",
  cilPaperclip = "cilPaperclip",
  cilPaperPlane = "cilPaperPlane",
  cilPen = "cilPen",
  cilPencil = "cilPencil",
  cilPeople = "cilPeople",
  cilPrint = "cilPrint",
  cilPuzzle = "cilPuzzle",
  cilReportSlash = "cilReportSlash",
  cilSave = "cilSave",
  cilSettings = "cilSettings",
  cilShare = "cilShare",
  cilShareAll = "cilShareAll",
  cilShareBoxed = "cilShareBoxed",
  cilSpeech = "cilSpeech",
  cilSpeedometer = "cilSpeedometer",
  cilSpreadsheet = "cilSpreadsheet",
  cilStar = "cilStar",
  cilSun = "cilSun",
  cilTruck = "cilTruck",
  cilTags = "cilTags",
  cilTask = "cilTask",
  cilTrash = "cilTrash",
  cilUnderline = "cilUnderline",
  cilUser = "cilUser",
  cilUserFemale = "cilUserFemale",
  cilUserFollow = "cilUserFollow",
  cilUserUnfollow = "cilUserUnfollow",
  cilEyedropper = "cilEyedropper",
  cilCart = "cilCart",
  cilMoney = "cilMoney",
  cilCash = "cilCash",
  cilPhone = "cilPhone",
}
